use super::Theme;
use super::definition::ThemeDef;

pub struct BuiltinTheme {
    pub name: &'static str,
    pub description: &'static str,
    pub is_light: bool,
    pub def: ThemeDef,
}

impl BuiltinTheme {
    pub fn to_theme(&self) -> Theme {
        let mut def = self.def.clone();
        def.is_light = self.is_light;
        def.into_theme(self.name)
    }
}

pub fn builtin_themes() -> Vec<BuiltinTheme> {
    vec![
        BuiltinTheme {
            name: "default",
            description: "Standard 16-color terminal ANSI palette",
            is_light: false,
            def: ThemeDef::default(),
        },
        BuiltinTheme {
            name: "catppuccin",
            description: "Soothing dark pastel palette (Mocha)",
            is_light: false,
            def: ThemeDef {
                background: Some("#1e1e2e".into()),
                foreground: Some("#cdd6f4".into()),
                black: Some("#45475a".into()),
                red: Some("#f38ba8".into()),
                green: Some("#a6e3a1".into()),
                yellow: Some("#f9e2af".into()),
                blue: Some("#89b4fa".into()),
                magenta: Some("#cba6f7".into()),
                cyan: Some("#89dceb".into()),
                white: Some("#bac2de".into()),
                bright_black: Some("#585b70".into()),
                bright_red: Some("#f38ba8".into()),
                bright_green: Some("#a6e3a1".into()),
                bright_yellow: Some("#f9e2af".into()),
                bright_blue: Some("#89b4fa".into()),
                bright_magenta: Some("#f5c2e7".into()),
                bright_cyan: Some("#94e2d5".into()),
                bright_white: Some("#a6adc8".into()),
                tool_error_bg: Some("#311b24".into()),
                ..Default::default()
            },
        },
        BuiltinTheme {
            name: "nord",
            description: "Arctic, north-bluish clean palette",
            is_light: false,
            def: ThemeDef {
                background: Some("#2e3440".into()),
                foreground: Some("#d8dee9".into()),
                black: Some("#3b4252".into()),
                red: Some("#bf616a".into()),
                green: Some("#a3be8c".into()),
                yellow: Some("#ebcb8b".into()),
                blue: Some("#81a1c1".into()),
                magenta: Some("#b48ead".into()),
                cyan: Some("#88c0d0".into()),
                white: Some("#e5e9f0".into()),
                bright_black: Some("#4c566a".into()),
                bright_red: Some("#bf616a".into()),
                bright_green: Some("#a3be8c".into()),
                bright_yellow: Some("#ebcb8b".into()),
                bright_blue: Some("#81a1c1".into()),
                bright_magenta: Some("#b48ead".into()),
                bright_cyan: Some("#8fbcbb".into()),
                bright_white: Some("#eceff4".into()),
                tool_error_bg: Some("#3b2d35".into()),
                ..Default::default()
            },
        },
        BuiltinTheme {
            name: "tokyo-night",
            description: "Modern dark neon purple and blue",
            is_light: false,
            def: ThemeDef {
                background: Some("#1a1b26".into()),
                foreground: Some("#c0caf5".into()),
                black: Some("#15161e".into()),
                red: Some("#f7768e".into()),
                green: Some("#9ece6a".into()),
                yellow: Some("#e0af68".into()),
                blue: Some("#7aa2f7".into()),
                magenta: Some("#bb9af7".into()),
                cyan: Some("#7dcfff".into()),
                white: Some("#a9b1d6".into()),
                bright_black: Some("#414868".into()),
                bright_red: Some("#f7768e".into()),
                bright_green: Some("#9ece6a".into()),
                bright_yellow: Some("#e0af68".into()),
                bright_blue: Some("#7aa2f7".into()),
                bright_magenta: Some("#bb9af7".into()),
                bright_cyan: Some("#2ac3de".into()),
                bright_white: Some("#c0caf5".into()),
                tool_error_bg: Some("#2d1f2d".into()),
                ..Default::default()
            },
        },
        BuiltinTheme {
            name: "dracula",
            description: "Vibrant dark purple and pink",
            is_light: false,
            def: ThemeDef {
                background: Some("#282a36".into()),
                foreground: Some("#f8f8f2".into()),
                black: Some("#21222c".into()),
                red: Some("#ff5555".into()),
                green: Some("#50fa7b".into()),
                yellow: Some("#f1fa8c".into()),
                blue: Some("#bd93f9".into()),
                magenta: Some("#ff79c6".into()),
                cyan: Some("#8be9fd".into()),
                white: Some("#f8f8f2".into()),
                bright_black: Some("#6272a4".into()),
                bright_red: Some("#ff6e6e".into()),
                bright_green: Some("#69ff94".into()),
                bright_yellow: Some("#ffffa5".into()),
                bright_blue: Some("#d6acff".into()),
                bright_magenta: Some("#ff92df".into()),
                bright_cyan: Some("#a4ffff".into()),
                bright_white: Some("#ffffff".into()),
                warning: Some("#ffb86c".into()),
                tool_error_bg: Some("#351f28".into()),
                ..Default::default()
            },
        },
        BuiltinTheme {
            name: "gruvbox",
            description: "Retro groove warm dark palette",
            is_light: false,
            def: ThemeDef {
                background: Some("#282828".into()),
                foreground: Some("#ebdbb2".into()),
                black: Some("#1d2021".into()),
                red: Some("#cc241d".into()),
                green: Some("#98971a".into()),
                yellow: Some("#d79921".into()),
                blue: Some("#458588".into()),
                magenta: Some("#b16286".into()),
                cyan: Some("#689d6a".into()),
                white: Some("#a89984".into()),
                bright_black: Some("#928374".into()),
                bright_red: Some("#fb4934".into()),
                bright_green: Some("#b8bb26".into()),
                bright_yellow: Some("#fabd2f".into()),
                bright_blue: Some("#83a598".into()),
                bright_magenta: Some("#d3869b".into()),
                bright_cyan: Some("#8ec07c".into()),
                bright_white: Some("#ebdbb2".into()),
                prompt: Some("#fe8019".into()),
                tool_error_bg: Some("#382323".into()),
                ..Default::default()
            },
        },
        BuiltinTheme {
            name: "monokai",
            description: "High-contrast classic code palette",
            is_light: false,
            def: ThemeDef {
                background: Some("#272822".into()),
                foreground: Some("#f8f8f2".into()),
                black: Some("#1e1f1c".into()),
                red: Some("#f92672".into()),
                green: Some("#a6e22e".into()),
                yellow: Some("#f4bf75".into()),
                blue: Some("#66d9ef".into()),
                magenta: Some("#ae81ff".into()),
                cyan: Some("#a1efe4".into()),
                white: Some("#f8f8f2".into()),
                bright_black: Some("#75715e".into()),
                bright_red: Some("#f92672".into()),
                bright_green: Some("#a6e22e".into()),
                bright_yellow: Some("#e6db74".into()),
                bright_blue: Some("#66d9ef".into()),
                bright_magenta: Some("#ae81ff".into()),
                bright_cyan: Some("#a1efe4".into()),
                bright_white: Some("#f9f8f5".into()),
                code_inline: Some("#fd971f".into()),
                tool_error_bg: Some("#3a2028".into()),
                ..Default::default()
            },
        },
        BuiltinTheme {
            name: "one-dark",
            description: "Balanced modern dark palette",
            is_light: false,
            def: ThemeDef {
                background: Some("#282c34".into()),
                foreground: Some("#abb2bf".into()),
                black: Some("#1e2127".into()),
                red: Some("#e06c75".into()),
                green: Some("#98c379".into()),
                yellow: Some("#d19a66".into()),
                blue: Some("#61afef".into()),
                magenta: Some("#c678dd".into()),
                cyan: Some("#56b6c2".into()),
                white: Some("#abb2bf".into()),
                bright_black: Some("#5c6370".into()),
                bright_red: Some("#e06c75".into()),
                bright_green: Some("#98c379".into()),
                bright_yellow: Some("#e5c07b".into()),
                bright_blue: Some("#61afef".into()),
                bright_magenta: Some("#c678dd".into()),
                bright_cyan: Some("#56b6c2".into()),
                bright_white: Some("#ffffff".into()),
                tool_error_bg: Some("#342329".into()),
                ..Default::default()
            },
        },
        BuiltinTheme {
            name: "solarized-dark",
            description: "Precision cyan and blue low-contrast dark",
            is_light: false,
            def: ThemeDef {
                background: Some("#002b36".into()),
                foreground: Some("#839496".into()),
                black: Some("#073642".into()),
                red: Some("#dc322f".into()),
                green: Some("#859900".into()),
                yellow: Some("#b58900".into()),
                blue: Some("#268bd2".into()),
                magenta: Some("#d33682".into()),
                cyan: Some("#2aa198".into()),
                white: Some("#eee8d5".into()),
                bright_black: Some("#586e75".into()),
                bright_red: Some("#cb4b16".into()),
                bright_green: Some("#586e75".into()),
                bright_yellow: Some("#657b83".into()),
                bright_blue: Some("#839496".into()),
                bright_magenta: Some("#6c71c4".into()),
                bright_cyan: Some("#93a1a1".into()),
                bright_white: Some("#fdf6e3".into()),
                tool_error_bg: Some("#382020".into()),
                ..Default::default()
            },
        },
        BuiltinTheme {
            name: "catppuccin-latte",
            description: "Soothing warm light palette for light terminals",
            is_light: true,
            def: ThemeDef {
                background: Some("#eff1f5".into()),
                foreground: Some("#4c4f69".into()),
                black: Some("#dce0e8".into()),
                red: Some("#d20f39".into()),
                green: Some("#40a02b".into()),
                yellow: Some("#df8e1d".into()),
                blue: Some("#1e66f5".into()),
                magenta: Some("#ea76cb".into()),
                cyan: Some("#04a5e5".into()),
                white: Some("#acb0be".into()),
                bright_black: Some("#9ca0b0".into()),
                bright_red: Some("#d20f39".into()),
                bright_green: Some("#40a02b".into()),
                bright_yellow: Some("#df8e1d".into()),
                bright_blue: Some("#1e66f5".into()),
                bright_magenta: Some("#8839ef".into()),
                bright_cyan: Some("#179299".into()),
                bright_white: Some("#5c5f77".into()),
                warning: Some("#fe640b".into()),
                tool_error_bg: Some("#fcdada".into()),
                ..Default::default()
            },
        },
    ]
}
