pub const BASELINE_TOOLS: &[&str] = &[
    "read",
    "write",
    "edit",
    "ls",
    "grep",
    "find",
    "fd",
    "rg",
    "fetch",
    "search",
    "todo",
    "ask_user_question",
    "subagent",
    "Agent",
    "get_subagent_result",
];

pub const BASELINE_BASH_ALLOW: &[&str] = &[
    "git status *",
    "git diff *",
    "git log *",
    "git show *",
    "git rev-parse *",
    "git remote -v*",
    "git remote show *",
    "git check-ignore *",
    "git branch --list *",
    "pwd*",
    "ls *",
    "dir *",
    "tree *",
    "stat *",
    "file *",
    "cd *",
    "grep *",
    "egrep *",
    "fgrep *",
    "rg *",
    "ag *",
    "fd *",
    "which *",
    "whereis *",
    "type *",
    "tokei *",
    "cloc *",
    "scc *",
    "cat *",
    "head *",
    "tail *",
    "wc *",
    "nl *",
    "strings *",
    "sort *",
    "uniq *",
    "cut *",
    "tr *",
    "column *",
    "fold *",
    "fmt *",
    "diff *",
    "cmp *",
    "jq *",
    "awk *",
    "uname *",
    "whoami*",
    "hostname*",
    "uptime*",
    "date*",
    "cal*",
    "echo *",
    "* --version",
    "* -v",
    "* --help",
    "* -h",
];

pub fn is_baseline_tool(tool: &str) -> bool {
    BASELINE_TOOLS.contains(&tool)
}

pub fn is_baseline_bash(command: &str) -> bool {
    BASELINE_BASH_ALLOW
        .iter()
        .any(|pattern| crate::permission::matcher::wildcard_match(pattern, command))
}
